language: php

env:
  global:
    - DEFAULT_COMPOSER_FLAGS="--prefer-dist --no-interaction --no-progress --optimize-autoloader"
    - TASK_STATIC_ANALYSIS=0
    - TASK_TESTS_COVERAGE=0

matrix:
  include:
    - php: "7.4"
      env:
        - TASK_STATIC_ANALYSIS=0 # set to 1 to enable static analysis
        - TASK_TESTS_COVERAGE=1

# faster builds on new travis setup not using sudo
sudo: false

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini || echo "xdebug is not installed"

install:
  - travis_retry composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install $DEFAULT_COMPOSER_FLAGS
  - |
    if [ $TASK_STATIC_ANALYSIS == 1 ]; then
      pecl install ast
    fi

before_script:
  - php --version
  - composer --version
  # enable code coverage
  - |
    if [ $TASK_TESTS_COVERAGE == 1 ]; then
        PHPUNIT_COVERAGE_FLAG="--coverage-clover=coverage.clover"
    fi

script:
  - phpdbg -qrr vendor/bin/phpunit --verbose $PHPUNIT_COVERAGE_FLAG
  - |
    if [ $TASK_STATIC_ANALYSIS == 1 ]; then
      composer phan
    fi
  - |
    if [ $TASK_STATIC_ANALYSIS == 1 ]; then
      cat analysis.txt
    fi

after_script:
  - |
    if [ $TASK_TESTS_COVERAGE == 1 ]; then
      travis_retry wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    fi


notifications:
  slack:
    -
      rooms:
        -
          secure: syqggATfXxv+gRO3jlVaIEZ2y3gkAF6BXC4Kp0qD5+gdfKRZo7kB1Pd5t6Jmg0KjNfyEAaKtxmxrhbw6Ttrna8f3z2inK/WM/J4jS7qPVBOQRYqUvbVOtM6daO/iPUVjM3YL+Tj05e0htqaFtzwcXrn25Hr4xV2djUBUdDEy0KPCP64c2bgSmyB4XKi//dPo3yLqNofePZHSGevkMji3TYpWh6bTCTjhZukYeI731xekgwq5dyyCOyBwfUyPZJqRaihdBEueBtddegFEs4+SFLB+KXQ1ee2C1iDU2WWH4/akz2tgt7RWjupNEGhdErY8GkdhW03GELQ/OO2kDLTfyQ1MlzY6/vnMnEl5SJenEHZuDtdnDXgK3aMPq4OfPQPkymkF0nE31uMmsdMqa8nxmFcBZfOszIcQ420EWl3kwyNH90JLMLXRNA0tfxIQc8389nNP4KtMkwRTUhvVvh20iaFPNskNecSOCWtny8Waif8WXGBzsT+kvNlK1795GZV71hcyxqZgwPrtvISEd8nr11y0X6rs7/ip7HQdOs7sHaVLecprzW6ua0Fzce9p5+NOqK02uh8U/VAeUGB27ENxZpx7DHEWPfYlFPVDguJcKi7548KGMu73A2R9HpRsCvA9QxtrisZicOer8PQM3y+NarHBn07O5DrKWfFhQr9ElFI=
      on_success: always
      on_failure: never
      on_pull_requests: false
    -
      rooms:
        -
          secure: JlFlJlt+Q4meoN6v1+cszkV2w51zvzvDffHDPK+pmXSdT5A2hfnYsHb95gpff1uYXHWZMR344ZY8syVcMhtdsXgy391HkRG2U1AkRVv+1CsjrnRqf76mYn+4Ud1zVidWrblsTBHyupnehlyzMxQB5L67GMS9YZCC0IRLGsf8Y1TzDVcGjYECHrun5N58AfjHFPM/mvZDt9mE3k/cFwyKVPw4kaQZszBN7E6JsV26B6I4Eie221ZM+a9uWwGr2k+rk6ACBZl0l86kxxPeedE0NdkvFrjfF7B25dUgnTXFg6QhPhMyuJf6+TIu9FtA0IjYK58amAWNcu/2bXsruc7bgDq08QdysJhu0JOXoAUyGXw5RaWHfQemxcpP5ExvfL8wA+0jWM3bbp5j7cBDY5bSmK8Ktd/meiALv8VP8xCez3OnerjACknEcrg15n+fAfytKZUotLyJF3jcViBiX5M5VE1ztSNf+V5FVpUF7qulhdPYt9iwbyLTEGI+3XgnxGp0Ob5K7d8PXRNRHeRHr0yYjiwJS/1Iel1ZkfEDvvu1NybGSIUYSL1orFxipBtivlTD+dYnQ/xc2D2zKkINuKnkL+xxToxFoYefO8CY+3OsEtTp8e0bkWHCzbNYIdZ1jQyd/xo9gOdJoXLRotOsWsLpWig4jZQvo7bb/YeZg5puzUA=
      on_success: never
      on_failure: always
      on_pull_requests: false
